print("EJERCICIO NUMERO 3, OPEN BOOT CAMP \n")
print("A continuación se hallara el Indice de Masa Corporal IMC \n \n")
print("Por favor digite aquí su peso en Kilogramos")
Kg=float(input())
print("Por favor digite su estatura en metros")
Mts=float(input())
IMC= (Kg/(Mts*Mts))
finalIMC = round (IMC, 2)
print("Tu Indice de Masa Corporal es: " , finalIMC , "\n \n")
print("FIN DE LA EJECUCION")